
language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install
  - cp config.yml.template config.yml
  - mysql -e "CREATE DATABASE devq" -uroot
  - vendor/bin/phinx --configuration=phinx.yml migrate --environment=development

script:
  - sh tests/travis.bash

addons:
    code_climate:
        repo_token: 8203fc037080060805e300c50fc5c101369bbb665e1681a662531da5be723ab1